language: php

php:
  - 7.2.10

before_install:
  - curl -sS https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer

install:
  - composer install

script:
  - true

after_script:
  - ls

global:
  - GH_REF: https://github.com/daisyhuli/PHP-APM.git
